---

- name: Converge
  hosts: all
  gather_facts: true
  vars:
    potos_xdg_autostart:
      - script: "test_1.sh.j2"
        runonlyonce: true
      - script: "test_2.sh.j2"
        runonlyonce: false

  tasks:

    - name: Setup files for testing
      ansible.builtin.debug:
        var: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/../files/potos_xdgautostart/usr/local/bin/*"

    - name: Run role
      ansible.builtin.include_role:
        name: 'ansible-role-potos_xdgautostart'
