---

- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Make directory for gnome autostart script(w/o installing gnome)
      ansible.builtin.shell:  # noqa: command-instead-of-module
        cmd: 'mkdir -p /etc/xdg/autostart'
      changed_when: false
