---

- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Make directory for gnome autostart script(w/o installing gnome)
      changed_when: false
      ansible.builtin.command: 'mkdir -p /etc/xdg/autostart' # noqa: command-instead-of-module
